<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import axios from '../../utils/axios'

const route = useRoute()
const router = useRouter()

const ris = ref(null)
const loading = ref(true)
const error = ref(null)

const formatDate = (dateString) => {
  if (!dateString) return 'N/A'
  return new Date(dateString).toLocaleString()
}

async function fetchRIS() {
  loading.value = true
  error.value = null
  try {
    const { data } = await axios.get(`/ris/${route.params.id}`)
    ris.value = {
      ...data.ris,
      items: data.ris.items.map((item) => ({
        ...item,
        issuedQty: item.issuedQty || 0
      }))
    }
  } catch (e) {
    error.value = e?.response?.data?.message || e.message
  } finally {
    loading.value = false
  }
}

onMounted(async () => {
  await fetchRIS()
  // Trigger browser print automatically once data is loaded
  setTimeout(() => window.print(), 300)
})
</script>

<template>
  <div class="print-container">
    <div v-if="loading" class="loading">Preparing print preview…</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <div v-else class="sheet">
      <header class="brand-header">
        <div class="brand-left">
          <img src="/favicon.ico" alt="Brand Logo" class="brand-logo" />
          <div class="brand-text">
            <div class="brand-name">Books & Clothes House</div>
            <div class="brand-sub">Cloud-Based IMS</div>
          </div>
        </div>
        <div class="doc-meta">
          <div class="doc-title">Requisition Issue Slip</div>
          <div class="doc-number">RIS #{{ ris.risNumber }}</div>
        </div>
      </header>

      <section class="meta">
        <div><span class="label">Created:</span> {{ formatDate(ris.createdAt) }}</div>
        <div><span class="label">Status:</span> {{ ris.status }}</div>
        <div><span class="label">Purpose:</span> {{ ris.purpose }}</div>
        <div><span class="label">Requestor:</span> {{ ris.requestor }}</div>
        <div v-if="ris.department"><span class="label">Department:</span> {{ ris.department }}</div>
        <div v-if="ris.notes"><span class="label">Notes:</span> {{ ris.notes }}</div>
      </section>

      <section>
        <table class="items">
          <thead>
            <tr>
              <th>Item</th>
              <th>SKU</th>
              <th class="num">Requested</th>
              <th class="num">Issued</th>
              <th class="num">Remaining</th>
              <th>Remarks</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in ris.items" :key="item.product">
              <td>{{ item.name }}</td>
              <td>{{ item.sku }}</td>
              <td class="num">{{ item.requestedQty }}</td>
              <td class="num">{{ item.issuedQty }}</td>
              <td class="num">{{ (item.requestedQty || 0) - (item.issuedQty || 0) }}</td>
              <td>{{ item.remarks }}</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section class="signature-block">
        <div class="signature">
          <div class="line"></div>
          <div class="role">Prepared By</div>
          <div class="name">{{ ris.requestor }}</div>
        </div>
        <div class="signature">
          <div class="line"></div>
          <div class="role">Checked By</div>
          <div class="name">__________________________</div>
        </div>
        <div class="signature">
          <div class="line"></div>
          <div class="role">Approved By</div>
          <div class="name">__________________________</div>
        </div>
        <div class="signature">
          <div class="line"></div>
          <div class="role">Issued By</div>
          <div class="name">__________________________</div>
        </div>
      </section>

      <footer class="footer">
        <div class="notes">This document is generated by Books & Clothes House IMS.</div>
        <div class="page">Page 1</div>
      </footer>
    </div>
  </div>
</template>

<style>
/* Page setup */
@page {
  size: A4;
  margin: 18mm 15mm;
}

html, body {
  background: #f5f5f5;
}

.print-container {
  display: flex;
  justify-content: center;
  padding: 24px;
}

.sheet {
  background: #fff;
  color: #111;
  width: 210mm;
  min-height: 297mm;
  box-shadow: 0 2px 12px rgba(0,0,0,0.12);
  padding: 18mm 15mm;
}

.brand-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 2px solid #222;
  padding-bottom: 12px;
}
.brand-left { display:flex; align-items:center; gap: 12px; }
.brand-logo { width: 48px; height: 48px; }
.brand-name { font-size: 18px; font-weight: 700; }
.brand-sub { font-size: 12px; color: #666; }
.doc-meta { text-align: right; }
.doc-title { font-size: 16px; font-weight: 600; }
.doc-number { font-size: 14px; color: #333; }

.meta { display:grid; grid-template-columns: 1fr 1fr; gap: 8px 24px; margin: 16px 0; }
.label { font-weight: 600; }

table.items { width: 100%; border-collapse: collapse; }
table.items th, table.items td { border: 1px solid #ddd; padding: 8px; }
table.items thead th { background: #fafafa; }
.num { text-align: right; }

.signature-block {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16px 24px;
  margin-top: 24px;
  page-break-inside: avoid;
}
.signature .line { height: 24px; border-bottom: 1px solid #444; margin-bottom: 6px; }
.signature .role { font-size: 12px; color: #555; }
.signature .name { font-size: 12px; color: #111; }

.footer {
  display: flex;
  justify-content: space-between;
  margin-top: 24px;
  font-size: 11px;
  color: #666;
}

/* Print-specific */
@media print {
  html, body { background: #fff; }
  .sheet { box-shadow: none; padding: 0; }
  .print-container { padding: 0; }
}

.page-break { page-break-after: always; }
</style>